#!/usr/bin/env bash
# print number from 1 to 20

i=1
while [ $i -le 20 ]
do
	case $i in
		4) echo "bad luck from China"
		;;
		9) echo "bad luck from Japan"
		;;
		17) echo "bad luck from Italy"
		;;
		esac
	echo "$i"
	i=$((i+1))
done
